### ISSUE TITLE
OpenERP won't install correctly

### ISSUE THREAD

**Issue by kvdb** [bmart/vagrant-openerp#1]
`vagrant up` runs all the way to the 'OpenERP is started!!' message, but fails along the way. This is the first issue I've seen:

```
/tmp/vagrant-shell: line 88: /usr/local/bin/virtualenvwrapper.sh: No such file or directory
Restarting nginx: nginx.
mkdir: cannot create directory `/var/lib/openerp/addons': No such file or directory
/tmp/vagrant-shell: line 105: cd: /var/lib/openerp: No such file or directory
/tmp/vagrant-shell: line 115: mkvirtualenv: command not found
/tmp/vagrant-shell: line 117: workon: command not found
```

I'm running precise, using virtualbox 4.1, vagrant 1.4.3.
I'd be happy to provide you with more details to find out what's the cause.

**Comment by bmart** [comment]
Hey, I will take a look and get back to you.

**Comment by bmart** [comment]
Ok,  Some sloppiness on my part. The useradd command line incorrect. I must have changed it at last minute and didn't test it enough.  The 2nd issue is actually related to the new PIP release 1.5 breaking setuptools. I switched out the new pip for an older pip. Destroyed my vm/recreated it and things are working. Email still requires manual install of postfix however.

**Comment by kvdb** [comment]
Issue solved, thanks.
