### ISSUE TITLE
merge efforts

### ISSUE THREAD

**Issue by blaggacao** [bmart/vagrant-openerp#4]
Hi Bmart,

as I'm getting more and more comfortable with github, vagrant, ansible, and docker, looking at your code, I got it, that you had exactly the same idea. 

Shouldn't we just merge our projects?

**Comment by bmart** [comment]
Sure, that is fine with me.  Sorry for the late reply. I've had a crazy
week.  Also, we better change the name to match the new branding *odoo. *I
need to catch up all your updates now.

**Comment by blaggacao** [comment]
I already was active..
I'll put you as adminstrator in the team, then you will be officially
colombian ;)))

I think we are cutting edge and serving a sane need with this project.
In my opinion Odoo should make havier use of virtualization techniques to
quit the hazzle of server administration.
It should be easy to everyone to get a running openerp to start boosting
his buisness, or to develop.

Have a look at the comments, issues, wikis I made to get an updated
overview of the topic :)

Now @ https://github.com/odoo-colombia/Odoo-VagrantUp

---

_David Arnold B.A. HSG_
_Gerente_

+57 315 304 1368
david@elaleman.co
www.elaleman.co

​El Alemán S.A.S, Carrera 13 # 93 - 40 P4, Bogotá D.C, Colombia

2014-05-16 20:14 GMT-05:00 bmart notifications@github.com:

> Sure, that is fine with me. Sorry for the late reply. I've had a crazy
> week. Also, we better change the name to match the new branding *odoo. *I
> need to catch up all your updates now.
>
